### PR TITLE
More descriptive names for node phases

### PR DESCRIPTION
**Pull request by jessitron**

### CODE REVIEW

**Comment by cdupuis** [comment]
I’m not a big fan of those longish descriptions. We tried to keep them close to what people  would run on the command line or see in the log output. 

Also if we change it here, we have to it everywhere for consistency.

**Comment by cdupuis** [comment]
What do others think @ddgenome @lievendoclo?

**Comment by ddgenome** [comment]
Isn't the larger issue rendering issues with longer names?

**Comment by lievendoclo** [comment]
I like the more descriptive names, just looks and feels more polished.

**Comment by cdupuis** [comment]
Yeah, it is a question of available space but also a lot about consistency: if we change it here, we have to change it in a lot of other places. For now I'd suggest that we park this until we have time to go through the entire code base to make it consistent.

**Pull request closed without merging**
